### ISSUE TITLE
`add-path` on GitHub Actions is going to be disabled on November 16th

### ISSUE THREAD

**Issue by thboop** [Mistuke/GhcChoco#10]
See the [blog post](https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/) for details on why.
It is being replaced by [environment variables](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-commands-for-github-actions#environment-files)

Currently, on install, we use the old commands to update the Path, for example (https://github.com/Mistuke/GhcChoco/blob/33ee2d0c4fbd40e0ef0c2bc7da81beb597421698/8.10.2/ghc/tools/chocolateyInstall.ps1#L65). 

This will start failing workflows on GitHub actions, resulting in users trying to install ghc from choco falling their job at that step.

This is also impacting the [setup-haskell](https://github.com/actions/setup-haskell/issues/44) action, which installs 
ghc using choco.

**Comment by Mistuke** [comment]
*sigh* ... If I read that correctly I need to do

`echo "{path}" >> $GITHUB_PATH` now?

**Comment by Mistuke** [comment]
Do you need all packages updated or can I just do the latest versions? i.e. `8.8.4` and `8.10.2`. I can't modify existing packages so submitting revisions of all the point releases will cause a versioning mess..

**Comment by thboop** [comment]
Thanks for taking a look so quickly!


> Do you need all packages updated or can I just do the latest versions? i.e. `8.8.4` and `8.10.2`. I can't modify existing packages so submitting revisions of all the point releases will cause a versioning mess..

Ideally all packages updated would be nice so users can manually specify older ones, but if that isn't possible at this time the latest would work well!

> echo "{path}" >> $GITHUB_PATH now?

Correct, you need to append the path to the file at  the path in the env variable `GITHUB_PATH`

If doing it in pwsh, it looks like
`echo "mypath" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append`

**Comment by Mistuke** [comment]
I've pushed updated versions of all affected stable releases (https://github.com/Mistuke/GhcChoco/commit/3630eb8fb521e238de241e23e2602c09d8882c0c):

* 8.10.2.2
* 8.10.1.1
* 8.8.2.1
* 8.8.3.2
* 8.8.4.1

They should be available as soon as they go through automated moderation on chocolatey which can take a couple of hours depending on server load.

**Comment by Mistuke** [comment]
Packages are available now. Thanks for the report!

**Comment by RyanGlScott** [comment]
I'm not sure if I'm doing something completely wrong here, but the newest versions don't appear to work correctly when I try to use them. [Here](https://ci.appveyor.com/project/RyanGlScott/code-page/build/job/gq67rgh1sfje1o4w) is the error I get when using GHC 8.10.2.2 (although I also experience the same error when using GHC 8.8.4.1):

```
Progress: Downloading ghc 8.10.2.2... 100%
Progress: Downloading chocolatey-core.extension 1.3.5.1... 100%
KB2919442 v1.0.20160915 [Approved]
kb2919442 package files install completed. Performing other installation steps.
Downloading KB2919442 64 bit
  from 'https://download.microsoft.com/download/D/6/0/D60ED3E0-93A5-4505-8F6A-8D0A5DA16C8A/Windows8.1-KB2919442-x64.msu'
Progress: 100% - Completed download of C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\KB2919442\1.0.20160915\Windows8.1-KB2919442-x64.msu (10.22 MB).
Download of Windows8.1-KB2919442-x64.msu (10.22 MB) completed.
Hashes match.
Installing KB2919442...
ERROR: Running ["C:\windows\System32\wusa.exe" "C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\KB2919442\1.0.20160915\Windows8.1-KB2919442-x64.msu" /quiet /norestart /log:"C:\Users\appveyor\AppData\Local\Temp\1\chocolatey\KB2919442.Install.evt" ] was not successful. Exit code was '1058'. See log for possible error messages.
The install of kb2919442 was NOT successful.
Error while running 'C:\ProgramData\chocolatey\lib\KB2919442\tools\ChocolateyInstall.ps1'.
 See log for details.
```

[Here](https://github.com/RyanGlScott/code-page/blob/c9121f5de5380fc79f8b3d2a87982b3d5ffc4abf/appveyor.yml) is the corresponding `appveyor.yml` file, if that is needed.

**Comment by Mistuke** [comment]
That looks like an issue with AppVeyor.. Error 1058 means the Windows installer service isn't running or not responding.

```
Error 1058: The service cannot be started, either because it is disabled or because it has no enabled devices associated with it.
```

The core of the issue is that Microsoft have forced the deprecation of older SSL protocols, which leaves older OSes unable to download using https.  https://blogs.windows.com/msedgedev/2020/03/31/tls-1-0-tls-1-1-schedule-update-edge-ie11/

Unfortunately while I don't personally care about these OSes and GHC doesn't even run on them I am forced to adhere to the chocolatey rules which validate the packages on older OSes as well.

This forces me for every new package to add a dependency on the Microsoft patch `kb2919355` to install support for newer SSL on these OSes.

On modern Windows these would already exist so the installer won't do anything. It would run, detect this and exit.  But in this case something went wrong with the AppVeyor configuration.

Now personally I think chocolatey is being stupid here, they should enforce this requirement at install time of chocolatey, not on every package.. but I lost that discussion.  So if this is repeatable a bug needs to be files with AppVeyor..

**Comment by RyanGlScott** [comment]
> So if this is repeatable a bug needs to be files with AppVeyor..

It definitely appears to be repeatable, as I've restarted the failing builds only to experience the same failures again.

**Comment by Mistuke** [comment]
This looks like an AppVeyor issue, they do indeed start with the Windows update service disabled. https://help.appveyor.com/discussions/problems/5616-not-able-to-build-due-to-problem-in-chocolateyinstallps1

adding

```
- ps: Set-Service wuauserv -StartupType Manual
```

before running the install should fix it. I really wish I didn't have to add this dependency... but if I "detect" chocolatey and use a non-secure link to get through validation that may get the packages revoked... Need to look into if merely providing a non-https fallback isn't against any rules.

**Comment by RyanGlScott** [comment]
Thanks! I can confirm that the workaround in https://github.com/Mistuke/GhcChoco/issues/10#issuecomment-730717731 works. (See RyanGlScott/code-page@40cce078d667e2201889ede3320a95c872301d04.)
