### ISSUE TITLE
GHC 9.0.1

### ISSUE THREAD

**Issue by gussen** [Mistuke/GhcChoco#13]
I installed GHC 9.0.1 2021-02-28, 'choco install ghc --version=9.0.1 -m' with just minor problems. It didn't install the versioned executables, ghc-9.0.1.exe, ghci-9.0.1.exe, ghcii-9.0.1.sh and haddock-9.0.1.exe. Way back when I installed 8.10.4 'choco install ghc --version=8.10.4 -m' it installed versioned executables. Maybe it can give you a clue finding out why 9.0.1 doesn't pass the automatic test.

**Comment by jneira** [comment]
See ghc issue here: https://gitlab.haskell.org/ghc/ghc/-/issues/19338
The tarball used in chocolatey from the official release ghc download page does not have those executables with suffix
Ideally next releases should have them again imo but maybe we could fix it for this release in chocolatey

**Comment by gussen** [comment]
I fixed it myself by using Chocolateys shimgen and that is probably a good solution to fix it in the chocolatey package. A big thanks for all the work done to improve the Haskell environment.

**Comment by Mistuke** [comment]
Thanks for the report. I will add a workaround in the package.

> Maybe it can give you a clue finding out why 9.0.1 doesn't pass the automatic test 

Sadly I don't think this is it. The output just stops.. Validation server doesn't actually give me an error

**Comment by Mistuke** [comment]
@thboop as a heads up, from GHC 9.0.1 the chocolatey package changes where it installs the package to for various reasons..

It's now going into `c:\tools` by default. You can set the environment variable `ChocolateyToolsLocation` before invoking to control where it goes so you can restore the old install location if you prefer.

**Comment by jneira** [comment]
The packaging is fixed for ghc-9.2: https://gitlab.haskell.org/ghc/ghc/-/issues/19338
