### ISSUE TITLE
GHC 9.2.1

### ISSUE THREAD

**Issue by kozross** [Mistuke/GhcChoco#17]
Would it be possible to package this? My particular use case is the [Haskell `setup` action](https://github.com/haskell/actions/tree/main/setup).

**Comment by Mistuke** [comment]
Ah yes, sorry wasn't aware it was released, missed the release email. I'll get it out

**Comment by Mistuke** [comment]
Done https://community.chocolatey.org/packages/ghc/9.2.1 my apologies for the delay, need to figure out a way to keep on top of releases.
