### ISSUE TITLE
Support GHC 9.2.6 and 9.2.7

### ISSUE THREAD

**Issue by andreasabel** [Mistuke/GhcChoco#19]
GHC 9.2.6 has been released, would be great to have it in Chocolatey!
- https://www.haskell.org/ghc/download_ghc_9_2_6.html

GHC 9.2.7 has also been released.

@Mistuke : Are you planning to package them for Chocolatey?
(I am a bit shy to ask, since GHCup has them, and maybe this is sufficient.  For the moment, `haskell/actions/setup` relies on choco, but this might change...)

**Comment by andreabedini** [comment]
@andreasabel it looks like 9.2.6 and 9.2.7 have been added a couple of days ago :tada:

**Comment by Mistuke** [comment]
@andreasabel oh dear, sorry I had missed this. I've whitelisted these emails now.

**Comment by andreasabel** [comment]
Great, these are officially supported now in https://github.com/haskell/actions/releases/tag/v2.3.4

**Comment by Mistuke** [comment]
I genuinely can't find the original notification in my email. It's like github never sent it.. Hrm..

**Comment by andreasabel** [comment]
Could be that github does not track mentions that are added in an edit.  I didn't mention @Mistuke in the OP, only in the edit later.  Are you subscribed to new issues here, or only to mentions?

**Comment by Mistuke** [comment]
I'm subscribed to everything, but it's quite weird. I just can't find the original email... I should keeo better track of releases. I don't get advanced notice on them so have to package after release.

I'll write a script to monitor the releases I think.
