### ISSUE TITLE
Being able to change ghc install directory

### ISSUE THREAD

**Issue by jneira** [Mistuke/GhcChoco#4]
Hi! I am adding jobs using chocolatey, ghc and cabal in haskell-ide-engine.
The default install dir of ghcs is the relative to choco install and afaiu it is fixed (correct me if i am wrong).

https://github.com/Mistuke/GhcChoco/blob/110d469b0bdb6939f9a1aea0f1656bb9b6c7f93b/8.8.2/ghc/tools/chocolateyInstall.ps1#L25

Being able to change the directory could help to:
* Install to another drive if the default one (typically `C:`) is almost full (the case of azure pipelines agent and the main reason to open this)
* Install to paths inside msys/mingw to reuse environment variables and scripts between linux and windows
  * You could download to `/opt/ghc/$GHC_VERSION/bin` and match the default install dir for several linux default installations

**Comment by jneira** [comment]
@Mistuke : this is not a big deal but i think it could be handy

**Comment by Mistuke** [comment]
I'll look into this for the 8.10 release. Shouldn't be that hard... Though I thought you could already do this by changing your choco install location but that seems to be a premium feature. 

> Install to paths inside msys/mingw to reuse environment variables and scripts between linux and windows 

I would be careful mixing msys things with it native applications.. the loader may load something incorrectly

**Comment by Mistuke** [comment]
So there is one problem with allowing people to do this. If the path is changed to something that contains spaces in it a lot of the tooling can't deal with it. like `configure` scripts. I can probably still allow it but reject paths with spaces..

**Comment by jneira** [comment]
Mmmm maybe same for long paths (although you resolved that for the more recent ghc versions)?

**Comment by Mistuke** [comment]
not completely, GHC and cabal themselves can handle it now, but GCC still can't. We'll make more progress here with `8.10` but `8.12` will probably be the first one that we've patched the majority of the APIs in for GCC and binutils etc.

**Comment by Mistuke** [comment]
Supported in ghc `8.10.2` https://chocolatey.org/packages/ghc/8.10.2
