### ISSUE TITLE
Include ghc-8.8.2 version

### ISSUE THREAD

**Issue by jneira** [Mistuke/GhcChoco#5]
Hi! Sure it will be added soon but ghc-8.8.1 is broken for building haskell-ide-engine due to https://gitlab.haskell.org/ghc/ghc/issues/17575 and it will be great test ghc-8.8.2 in azure
Many thanks!

**Comment by Mistuke** [comment]
I have created the packages but I haven't released it because I am still working to get the 32-bit distribution for 8.8.2 released from GHC HQ.

So I'm giving it some time since it's if I release the package it's immutable and will break 32-bit support.

**Comment by Mistuke** [comment]
Package has been uploaded. should be available in an hour or so

**Comment by jneira** [comment]
Great news! many thanks
